# Generated by Django 3.2.7 on 2021-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
